config/routes.rb
GroceryList::Application.routes.draw do

  ActiveAdmin.routes(self)

  devise_for :admins, ActiveAdmin::Devise.config

  devise_for :users, :path => '/', :path_names => {
    :sign_in => 'login',
    :sign_out => 'logout',
    :sign_up => 'register'
  }

  authenticated :user do
    root :to => 'lists#index'
  end

  resources :lists do
    resources :list_items do
      put 'position', :on => :member
    end
  end

  namespace :settings do
    root :to => 'base#index'
    resource :account, :only => [:edit, :update]
  end

  root :to => 'welcome#index'

  match '/about' => 'static#about', :as => :about
  match '/contact' => 'static#contact', :as => :contact
  match '/help' => 'static#help', :as => :help
  match '/terms' => 'static#terms', :as => :terms

end

app/models/list.rb
class List < ActiveRecord::Base

  after_create :owner_subscription

  attr_accessible :name

  validates :name, :presence => true

  belongs_to :owner, :class_name => "User", :foreign_key => :user_id

  has_many  :list_items, :dependent => :destroy
  has_many  :products, :dependent => :destroy

  has_many  :list_users
  has_many  :users, :through => :list_users

private

  def owner_subscription
    list_user = ListUser.new
    list_user.user = User.find(self.user_id)
    list_user.list = self
    list_user.save
  end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  def index
    @lists = current_user.lists
  end

  def show
    @list = current_user.lists.find params[:id]
    @li = ListItem.new
    @categories = Category.all
  end

  def new
    @list = List.new
  end

  def create
    @list = current_user.owned_lists.new params[:list]

    if @list.save
      flash[:notice] = "#{@list.name} was created."
      redirect_to list_path(@list)
    else
      flash[:alert] = "There was a problem creating #{@list.name}."
      redirect_to :back
    end
  end


  def edit
    @list = List.find params[:id]
  end

  def update
    @list = List.find params[:id]

    if @list.update_attributes params[:list]
      flash[:notice] = "#{@list.name} was updated."
      redirect_to lists_path
    else
      flash[:alert] = "#{@list.name} was not updated."
      redirect_to :back
    end
  end


  def destroy
    @list = List.find params[:id]

    if @list.destroy
      flash[:notice] = "#{@list.name} has been deleted."
    else
      flash[:alert] = "#{@list.name} could not be deleted."
    end

    redirect_to lists_path
  end


end

app/views/lists/_form.html.haml
= simple_form_for(@list) do |f|
  %fieldset.name
    = f.input :name, :label => 'name', :required => true
  %fieldset.buttons
    = link_to 'Create List', void_path, :class => 'submit btn'
  %footer
    = link_to 'cancel', :back, :class => 'cancel'

app/views/lists/_list.html.haml
%section.list[@list]
  %header
    %h1.section
      %span.text
        Grocery List
      %span.meta
        = "(#{@list.list_items.count})"
  .content
    - @categories.each do |category|
      .category[category]{:class => "#{category.to_parameter}"}
        %header
          %h1.section
            %span.text
              = category.title
        .list_items
          - @list.list_items.by_category(category).each do |li|
            .list_item[li]
              .name
                name:
                = li.product.name
              .quantity
                quantity:
                = li.quantity
              .note
                note:
                = li.note
              .user
                requested by:
                = li.user.display_name
              .actions
                = link_to "edit", edit_list_list_item_path(@list, li)
                = link_to "delete", list_list_item_path(@list, li), :method => :delete, :confirm => "Are you sure you want to delete #{li.product.name} from your list?"

app/views/lists/edit.html.haml
%h1.page Edit List
= render :partial => "form"

app/views/lists/index.html.haml
%h1.page Dashboard

= link_to "Create a List", new_list_path

%section.lists[@list]
  %header
    %h1.section
      %span.text
        Grocery Lists
      %span.meta
        = "(#{@lists.count})"
  .content
    - @lists.each do |list|
      %header
        %h1.section
          %span.text
            = link_to list.name, list_path(list)
            .actions
              = link_to "edit", edit_list_path(list)
              = link_to "delete", list_path(list), :method => :delete, :confirm => "Are you sure you want to delete #{list.name} list?"

app/views/lists/new.html.haml
%h1.page Create a List
= render :partial => "form"

app/views/lists/show.html.haml
%h1.page "#{@list.name}"
= render :partial => "list_items/form"
= render :partial => "list"