config/routes.rb
GroceryList::Application.routes.draw do

  ActiveAdmin.routes(self)

  devise_for :admins, ActiveAdmin::Devise.config

  devise_for :users, :path => '/', :path_names => {
    :sign_in => 'login',
    :sign_out => 'logout',
    :sign_up => 'register'
  }

  authenticated :user do
    root :to => 'lists#index'
  end

  resources :lists do
    resources :list_items do
      put 'position', :on => :member
    end
  end

  namespace :settings do
    root :to => 'base#index'
    resource :account, :only => [:edit, :update]
  end

  root :to => 'welcome#index'

  match '/about' => 'static#about', :as => :about
  match '/contact' => 'static#contact', :as => :contact
  match '/help' => 'static#help', :as => :help
  match '/terms' => 'static#terms', :as => :terms

end

app/views/layouts/_footer.html.haml
%footer.site

  %ul.copyright
    %li Copyright © 2012 Grocery List

  %ul.static
    %li= link_to "About", about_path
    %li= link_to "Contact", contact_path
    %li= link_to "Help", help_path
    %li= link_to "Terms of Service", terms_path

app/views/layouts/_header.html.haml
%header.site

  %h1.logo
    = link_to root_path do
      %i.icon_cart
      %i.icon_cart
      %i.icon_cart

  - if user_signed_in?
    %ul
      %li
        Hello
        = link_to current_user.display_name, settings_root_path
      %li= link_to 'logout', destroy_user_session_path, method: :delete
  - else
    %ul
      %li= link_to 'register', new_user_registration_path
      %li= link_to 'login', new_user_session_path

= flash_messages

app/views/layouts/application.html.haml
!!!

%html
  %head
    %title Grocery List
    = csrf_meta_tags
    = stylesheet_link_tag "application"

%body{:class => body_class}

  #container
    = render 'layouts/header'

    #content
      = yield
      
    #push
    
  = render 'layouts/footer'

  = javascript_include_tag "application"